### PR TITLE
GSoC Proposal : Anomaly Detection of CoreDNS Server through Machine Learning

### PR DESCRIPTION
**Pull request by cekbote**
Anomaly Detection of CoreDNS Server through Machine Learning

### CODE REVIEW

**Comment by cekbote** [comment]
@greenpau @yongtang Apologies for the messy commits. There was some issue with my computer, which was making it repeatedly crash. Hence, I was committing the changes the minute I made them.

**Comment by greenpau** [comment]
@Chanakya-Ekbote , please accept DCO and rebase your commits.

**Comment by cekbote** [comment]
>

**Comment by cekbote** [comment]
@greenpau Done rebasing. Sorry about that.

**Comment by cekbote** [comment]
@greenpau @yongtang Could you please go through the proposal and suggest some changes? Thank you.

**Comment by cekbote** [comment]
@greenpau @yongtang Could I submit the proposal then, if you are ok with the current proposal.

**Comment by greenpau** [comment]
@Chanakya-Ekbote , I did not have a chance to review it yet. Perhaps, I will get to it over the weekend. Please be mindful of the C-19 crisis in NY. Personally, I work for a hospital in NYC and we are getting hit hard.

**Comment by cekbote** [comment]
@greenpau Apologies. Please take your time, please take care and stay safe. I wasn't aware that you worked for a hospital.

**Comment by yongtang** [comment]
@Chanakya-Ekbote  as the proposal has been accepted, can you update the PR to change the status to `Accepted`? You also need to fix DCO issues. I think after that the PR could be merged.

**Comment by cekbote** [comment]
> 
> 
> @Chanakya-Ekbote as the proposal has been accepted, can you update the PR to change the status to `Accepted`? You also need to fix DCO issues. I think after that the PR could be merged.

I've changed the status and acccepted the DCO. Apologies for not doing it before.

**Comment by yongtang** [comment]
@Chanakya-Ekbote One more small update, can you change the sponsor to:
```
Yong Tang (@yongtang), Paul Greenberg (@greenpau)
```

After that we can just merge.

**Comment by cekbote** [comment]
> 
> 
> @Chanakya-Ekbote One more small update, can you change the sponsor to:
> 
> ```
> Yong Tang (@yongtang), Paul Greenberg (@greenpau)
> ```
> 
> After that we can just merge.

I have added the sponsers. Please let me know if I've to make any other changes.

**Review by yongtang — APPROVED** [review]

**Pull request merged**
